### ISSUE TITLE
[BUG] - CuPy not installing correctly

### ISSUE THREAD

**Issue by youdontknowmu** [Hkshoonya/nvidia-broadcast-linux#9]
## Describe the Bug

Hi there,
 CuPy install not working on Linux Mint 22.3

## Steps to Reproduce

1.Run 
git clone https://github.com/Hkshoonya/nvidia-broadcast-linux.git
cd nvidia-broadcast-linux
./install.sh

2. Everything is fine until it says CUDA not available
3. It goes to cupy install step, then can't install it when I type Y to unstall CuPy

## System Info

- **OS**: Mint 22.3
- **GPU**: 5070ti
- **NVIDIA Driver**: | NVIDIA-SMI 595.58.03              Driver Version: 595.58.03      CUDA Version: 13.2     |
- **Python**: python3 --version`
- **App version**: (run `python -c "import nvbroadcast; print(nvbroadcast.__version__)"`)
This command is not working -> says 
python -c "import nvbroadcast; print(nvbroadcast.__version__)"
command « python » not found, voulez-vous dire :
  command « python3 » du deb python3
  command « python » du deb python-is-python3

## Terminal Output

Verifying core dependencies...
  numpy ... OK
  cv2 ... OK
  mediapipe ... OK
  onnxruntime ... OK
  PIL ... OK
  psutil ... OK
  onnx ... OK
  pyrnnoise ... OK

Verifying GPU acceleration...
  WARNING: CUDA not available, will run on CPU (slower)

─────────────────────────────────────────
  Optional Packages
─────────────────────────────────────────

  These unlock premium features. You can install them now or later.
  If skipped, the app will prompt when you select a mode that needs them.

  1) CuPy CUDA (~800MB) — Unlocks:
     - Killer mode (48fps, fused CUDA kernel compositing)
     - Zeus mode (33fps, GPU-optimized inference)
     - DocZeus mode (full quality + 0.1ms fused compositing)
     - GPU alpha blending (150x faster than CPU)

  Install CuPy? [Y/n] Y
  Installing CuPy (this may take a few minutes)...

ERROR: Installation failed at line 498 (exit code 0)
Please report this issue with the output above.

```
paste any error messages here
```

## Screenshots (if applicable)

<img width="626" height="533" alt="Image" src="https://github.com/user-attachments/assets/8dd7dc7b-722b-4c96-8243-a27e8a2eb576" />

<img width="1187" height="67" alt="Image" src="https://github.com/user-attachments/assets/c0c018de-bd73-4c6b-817c-9b86f07896d3" />

**Comment by Hkshoonya** [comment]
Quick update: the latest released version is now `v1.1.9`.

The original CuPy installer failure from this issue was fixed in `v1.1.8`, and `v1.1.9` is now the recommended version because it also fixes a separate meeting-transcription dependency install path that we found during release verification.

Please retest with `v1.1.9` instead of `v1.1.8`.

For source install:

```bash
git pull
./install.sh
```

For Snap:

```bash
sudo snap refresh nvbroadcast
nvbroadcast
```

For `.deb` users, install the latest package from the `v1.1.9` release:

```bash
sudo apt install ./nvbroadcast_1.1.9-1_all.deb
nvbroadcast
```

Release link:
https://github.com/Hkshoonya/nvidia-broadcast-linux/releases/tag/v1.1.9

I am still leaving this issue open until you confirm the CuPy installer path works on your Mint 22.3 + RTX 5070 Ti system.
